name: fsl challenge

on:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 15
      - name: Install dependencies
        run: |
          cd codebase/rdicidr-0.1.0
          npm install
      - name: Linter (ESLint)
        run: |
          cd codebase/rdicidr-0.1.0
          npm run lint
      - name: Formatter (Prettier)
        run: |
          cd codebase/rdicidr-0.1.0
          npm install -g prettier
          npm run prettier
      - name: Test (Jest)
        run: |
          cd codebase/rdicidr-0.1.0
          CI=true npm run test
      - name: Build
        run: |
          cd codebase/rdicidr-0.1.0
          npm run build          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: etaques
          password: ${{ secrets.GHCI_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/etaques/devops-ci-challenge2:latest
        
    
